name: Raise refresh ticket in JIRA

on: 
  workflow_call:
    inputs:
      JIRA_ACCOUNT:
        required: true
        type: string
      JIRA_USERNAME:
        required: true
        type: string      
      CONTENT_NAME:
        required: true
        type: string         
      CONTENT_REPO:
        required: true
        type: string                
jobs:
  jiraIssueCreation:
    name: Raise refresh ticket in JIRA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Jira Creation Demo
        uses: bryannice/gitactions-jira-issue-creation@master
        env:
          JIRA_ACCOUNT_URL: https://${{ inputs.JIRA_ACCOUNT }}/
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_ISSUE_DESCRIPTION: 'This content needs to validated as a refresh flag has been triggered. Repo: ${{ inputs.CONTENT_REPO}} '
          JIRA_ISSUE_SUMMARY: Refresh content ${{ inputs.CONTENT_NAME }}
          JIRA_ISSUE_TYPE: Task
          JIRA_PROJECT: JT
          JIRA_USERNAME: ${{ inputs.JIRA_USERNAME }}